# Generated by Django 4.2.6 on 2023-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y', '0004_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='likedBy',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
